include-file = ~/.config/polybar/modules.ini
include-file = ~/.config/polybar/catppuccin-mocha.ini

[colors]
background = ${colors.base}
background-alt = ${colors.base}
foreground = ${colors.text}
primary = ${colors.text}
secondary = ${colors.text}
alert = ${colors.red}
disabled = ${colors.surface0}

[bar/mybar]
width = 100%
height = 25pt
radius = 0

; dpi = 96

background = ${colors.background}
foreground = ${colors.foreground}

line-size = 3pt

padding-left = 1
padding-right = 1

module-margin = 0

;font-0 = Iosevka NFP:size=13;4
;font-1 = Iosevka NFP:size=13;5
font-0 = GohuFont uni11 Nerd Font Propo:size=14;4
font-1 = GohuFont uni11 Nerd Font Propo:size=14;5

modules-left = xworkspaces
modules-center = date
modules-right = network backlight pulseaudio bat0 bat1

cursor-click = pointer
cursor-scroll = ns-resize

enable-ipc = true

[settings]
screenchange-reload = true
pseudo-transparency = true

; vim:ft=dosini
