# vim:fileencoding=utf-8:foldmethod=marker

#: Fonts {{{

font_family	Iosevka NFM

font_size 13.0

#: }}}

#: Text cursor customization {{{

#: }}}

#: Scrollback {{{

#: }}}

#: Mouse {{{

#: Mouse actions {{{

#: }}}

#: }}}

#: Performance tuning {{{

#: }}}

#: Terminal bell {{{

enable_audio_bell no

#: }}}

#: Window layout {{{

enabled_layouts grid

window_margin_width 2

inactive_text_alpha 0.4
#: }}}

#: Tab bar {{{

#: }}}

#: Color scheme {{{

background_opacity 0.8

#: The color table {{{

#: }}}

#: }}}

#: Advanced {{{

#: }}}

#: OS specific tweaks {{{

#: }}}

#: Keyboard shortcuts {{{

#: Clipboard {{{

#: }}}

#: Scrolling {{{

#: }}}

#: Window management {{{

#: }}}

#: Tab management {{{

#: }}}

#: Layout management {{{

#: }}}

#: Font sizes {{{

#: }}}

#: Select and act on visible text {{{

#: }}}

#: Miscellaneous {{{

#: }}}

#: }}}

# BEGIN_KITTY_THEME
# Catppuccin-Mocha
include current-theme.conf
# END_KITTY_THEME
